<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260218072038 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cgpa_record (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gpa NUMERIC(3, 2) NOT NULL, record_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_82039A404DFD750C ON cgpa_record (record_id)');
        $this->addSql('CREATE TABLE kpi_record (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(25) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, level SMALLINT DEFAULT NULL, category SMALLINT DEFAULT NULL, tags JSON DEFAULT NULL, notes TEXT DEFAULT NULL, record_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AE148D84DFD750C ON kpi_record (record_id)');
        $this->addSql('CREATE TABLE semester_record (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, semester SMALLINT NOT NULL, academic_year VARCHAR(9) NOT NULL, student_id VARCHAR(36) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AE2A1734CB944F1A ON semester_record (student_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_student_semester_year ON semester_record (student_id, semester, academic_year)');
        $this->addSql('ALTER TABLE cgpa_record ADD CONSTRAINT FK_82039A404DFD750C FOREIGN KEY (record_id) REFERENCES semester_record (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kpi_record ADD CONSTRAINT FK_AE148D84DFD750C FOREIGN KEY (record_id) REFERENCES semester_record (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE semester_record ADD CONSTRAINT FK_AE2A1734CB944F1A FOREIGN KEY (student_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cgpa_record DROP CONSTRAINT FK_82039A404DFD750C');
        $this->addSql('ALTER TABLE kpi_record DROP CONSTRAINT FK_AE148D84DFD750C');
        $this->addSql('ALTER TABLE semester_record DROP CONSTRAINT FK_AE2A1734CB944F1A');
        $this->addSql('DROP TABLE cgpa_record');
        $this->addSql('DROP TABLE kpi_record');
        $this->addSql('DROP TABLE semester_record');
    }
}
