<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260219004254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE challenge (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, challenge TEXT NOT NULL, plan TEXT NOT NULL, notes TEXT DEFAULT NULL, record_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D70989514DFD750C ON challenge (record_id)');
        $this->addSql('ALTER TABLE challenge ADD CONSTRAINT FK_D70989514DFD750C FOREIGN KEY (record_id) REFERENCES semester_record (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE challenge DROP CONSTRAINT FK_D70989514DFD750C');
        $this->addSql('DROP TABLE challenge');
    }
}
