<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260215000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user and intake batch tables for authentication';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE intake_batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE app_user (id VARCHAR(36) NOT NULL, intake_batch_id INT DEFAULT NULL, identifier VARCHAR(64) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, role SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_identifier ON app_user (identifier)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON app_user (email)');
        $this->addSql('CREATE INDEX idx_app_user_intake_batch_id ON app_user (intake_batch_id)');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT fk_app_user_intake_batch_id FOREIGN KEY (intake_batch_id) REFERENCES intake_batch (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE app_user DROP CONSTRAINT fk_app_user_intake_batch_id');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE intake_batch');
    }
}
