<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260219100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mentee (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mentorship_id SMALLINT NOT NULL, student_id VARCHAR(36) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9290F9339CF49FD ON mentee (mentorship_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_mentee_student ON mentee (student_id)');
        $this->addSql('CREATE TABLE mentorship (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lecturer_id VARCHAR(36) NOT NULL, intake_batch_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ADE55FF4BA2D8762 ON mentorship (lecturer_id)');
        $this->addSql('CREATE INDEX IDX_ADE55FF4120F8C4B ON mentorship (intake_batch_id)');
        $this->addSql('ALTER TABLE mentee ADD CONSTRAINT FK_F9290F9339CF49FD FOREIGN KEY (mentorship_id) REFERENCES mentorship (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mentee ADD CONSTRAINT FK_F9290F93CB944F1A FOREIGN KEY (student_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mentorship ADD CONSTRAINT FK_ADE55FF4BA2D8762 FOREIGN KEY (lecturer_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mentorship ADD CONSTRAINT FK_ADE55FF4120F8C4B FOREIGN KEY (intake_batch_id) REFERENCES intake_batch (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mentee DROP CONSTRAINT FK_F9290F9339CF49FD');
        $this->addSql('ALTER TABLE mentee DROP CONSTRAINT FK_F9290F93CB944F1A');
        $this->addSql('ALTER TABLE mentorship DROP CONSTRAINT FK_ADE55FF4BA2D8762');
        $this->addSql('ALTER TABLE mentorship DROP CONSTRAINT FK_ADE55FF4120F8C4B');
        $this->addSql('DROP TABLE mentee');
        $this->addSql('DROP TABLE mentorship');
    }
}
