<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260218072151 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE kpi_aim (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cgpa_target NUMERIC(3, 2) NOT NULL, activity_targets JSON NOT NULL, competition_targets JSON NOT NULL, certificate_targets JSON NOT NULL, student_id VARCHAR(36) DEFAULT NULL, lecturer_id VARCHAR(36) DEFAULT NULL, batch_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D69AAC74CB944F1A ON kpi_aim (student_id)');
        $this->addSql('CREATE INDEX IDX_D69AAC74BA2D8762 ON kpi_aim (lecturer_id)');
        $this->addSql('CREATE INDEX IDX_D69AAC74F39EBE7A ON kpi_aim (batch_id)');
        $this->addSql('ALTER TABLE kpi_aim ADD CONSTRAINT FK_D69AAC74CB944F1A FOREIGN KEY (student_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kpi_aim ADD CONSTRAINT FK_D69AAC74BA2D8762 FOREIGN KEY (lecturer_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kpi_aim ADD CONSTRAINT FK_D69AAC74F39EBE7A FOREIGN KEY (batch_id) REFERENCES intake_batch (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE kpi_aim DROP CONSTRAINT FK_D69AAC74CB944F1A');
        $this->addSql('ALTER TABLE kpi_aim DROP CONSTRAINT FK_D69AAC74BA2D8762');
        $this->addSql('ALTER TABLE kpi_aim DROP CONSTRAINT FK_D69AAC74F39EBE7A');
        $this->addSql('DROP TABLE kpi_aim');
    }
}
