/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthSettingsRouteRouteImport } from './routes/_auth/settings/route'
import { Route as AuthStudentRouteRouteImport } from './routes/_auth/_student/route'
import { Route as AuthStaffRouteRouteImport } from './routes/_auth/_staff/route'
import { Route as AuthLecturerRouteRouteImport } from './routes/_auth/_lecturer/route'
import { Route as AuthSettingsUserSessionsRouteImport } from './routes/_auth/settings/user-sessions'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthStudentKpiOverviewRouteImport } from './routes/_auth/_student/kpi/overview'
import { Route as AuthStudentKpiChallengesRouteImport } from './routes/_auth/_student/kpi/challenges'
import { Route as AuthStaffStaffManageStudentsRouteImport } from './routes/_auth/_staff/staff/manage-students'
import { Route as AuthStaffStaffManageLecturersRouteImport } from './routes/_auth/_staff/staff/manage-lecturers'
import { Route as AuthStaffStaffIntakesRouteImport } from './routes/_auth/_staff/staff/intakes'
import { Route as AuthLecturerMentorshipsStudentsRouteImport } from './routes/_auth/_lecturer/mentorships/students'
import { Route as AuthLecturerMentorshipsDashboardRouteImport } from './routes/_auth/_lecturer/mentorships/dashboard'
import { Route as AuthStudentKpiTargetRouteRouteImport } from './routes/_auth/_student/kpi/target/route'
import { Route as AuthStudentKpiRecordsRouteRouteImport } from './routes/_auth/_student/kpi/records/route'
import { Route as AuthStudentKpiAcademicsRouteRouteImport } from './routes/_auth/_student/kpi/academics/route'
import { Route as AuthStudentKpiTargetIndexRouteImport } from './routes/_auth/_student/kpi/target/index'
import { Route as AuthStudentKpiRecordsIndexRouteImport } from './routes/_auth/_student/kpi/records/index'
import { Route as AuthStudentKpiAcademicsIndexRouteImport } from './routes/_auth/_student/kpi/academics/index'
import { Route as AuthStudentKpiTargetEditRouteImport } from './routes/_auth/_student/kpi/target/edit'
import { Route as AuthStudentKpiRecordsAnalyticsRouteImport } from './routes/_auth/_student/kpi/records/analytics'
import { Route as AuthStudentKpiAcademicsAnalyticsRouteImport } from './routes/_auth/_student/kpi/academics/analytics'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentRouteRoute = AuthStudentRouteRouteImport.update({
  id: '/_student',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStaffRouteRoute = AuthStaffRouteRouteImport.update({
  id: '/_staff',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLecturerRouteRoute = AuthLecturerRouteRouteImport.update({
  id: '/_lecturer',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsUserSessionsRoute =
  AuthSettingsUserSessionsRouteImport.update({
    id: '/user-sessions',
    path: '/user-sessions',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthStudentKpiOverviewRoute = AuthStudentKpiOverviewRouteImport.update({
  id: '/kpi/overview',
  path: '/kpi/overview',
  getParentRoute: () => AuthStudentRouteRoute,
} as any)
const AuthStudentKpiChallengesRoute =
  AuthStudentKpiChallengesRouteImport.update({
    id: '/kpi/challenges',
    path: '/kpi/challenges',
    getParentRoute: () => AuthStudentRouteRoute,
  } as any)
const AuthStaffStaffManageStudentsRoute =
  AuthStaffStaffManageStudentsRouteImport.update({
    id: '/staff/manage-students',
    path: '/staff/manage-students',
    getParentRoute: () => AuthStaffRouteRoute,
  } as any)
const AuthStaffStaffManageLecturersRoute =
  AuthStaffStaffManageLecturersRouteImport.update({
    id: '/staff/manage-lecturers',
    path: '/staff/manage-lecturers',
    getParentRoute: () => AuthStaffRouteRoute,
  } as any)
const AuthStaffStaffIntakesRoute = AuthStaffStaffIntakesRouteImport.update({
  id: '/staff/intakes',
  path: '/staff/intakes',
  getParentRoute: () => AuthStaffRouteRoute,
} as any)
const AuthLecturerMentorshipsStudentsRoute =
  AuthLecturerMentorshipsStudentsRouteImport.update({
    id: '/mentorships/students',
    path: '/mentorships/students',
    getParentRoute: () => AuthLecturerRouteRoute,
  } as any)
const AuthLecturerMentorshipsDashboardRoute =
  AuthLecturerMentorshipsDashboardRouteImport.update({
    id: '/mentorships/dashboard',
    path: '/mentorships/dashboard',
    getParentRoute: () => AuthLecturerRouteRoute,
  } as any)
const AuthStudentKpiTargetRouteRoute =
  AuthStudentKpiTargetRouteRouteImport.update({
    id: '/kpi/target',
    path: '/kpi/target',
    getParentRoute: () => AuthStudentRouteRoute,
  } as any)
const AuthStudentKpiRecordsRouteRoute =
  AuthStudentKpiRecordsRouteRouteImport.update({
    id: '/kpi/records',
    path: '/kpi/records',
    getParentRoute: () => AuthStudentRouteRoute,
  } as any)
const AuthStudentKpiAcademicsRouteRoute =
  AuthStudentKpiAcademicsRouteRouteImport.update({
    id: '/kpi/academics',
    path: '/kpi/academics',
    getParentRoute: () => AuthStudentRouteRoute,
  } as any)
const AuthStudentKpiTargetIndexRoute =
  AuthStudentKpiTargetIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStudentKpiTargetRouteRoute,
  } as any)
const AuthStudentKpiRecordsIndexRoute =
  AuthStudentKpiRecordsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStudentKpiRecordsRouteRoute,
  } as any)
const AuthStudentKpiAcademicsIndexRoute =
  AuthStudentKpiAcademicsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStudentKpiAcademicsRouteRoute,
  } as any)
const AuthStudentKpiTargetEditRoute =
  AuthStudentKpiTargetEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthStudentKpiTargetRouteRoute,
  } as any)
const AuthStudentKpiRecordsAnalyticsRoute =
  AuthStudentKpiRecordsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthStudentKpiRecordsRouteRoute,
  } as any)
const AuthStudentKpiAcademicsAnalyticsRoute =
  AuthStudentKpiAcademicsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthStudentKpiAcademicsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/user-sessions': typeof AuthSettingsUserSessionsRoute
  '/kpi/academics': typeof AuthStudentKpiAcademicsRouteRouteWithChildren
  '/kpi/records': typeof AuthStudentKpiRecordsRouteRouteWithChildren
  '/kpi/target': typeof AuthStudentKpiTargetRouteRouteWithChildren
  '/mentorships/dashboard': typeof AuthLecturerMentorshipsDashboardRoute
  '/mentorships/students': typeof AuthLecturerMentorshipsStudentsRoute
  '/staff/intakes': typeof AuthStaffStaffIntakesRoute
  '/staff/manage-lecturers': typeof AuthStaffStaffManageLecturersRoute
  '/staff/manage-students': typeof AuthStaffStaffManageStudentsRoute
  '/kpi/challenges': typeof AuthStudentKpiChallengesRoute
  '/kpi/overview': typeof AuthStudentKpiOverviewRoute
  '/kpi/academics/analytics': typeof AuthStudentKpiAcademicsAnalyticsRoute
  '/kpi/records/analytics': typeof AuthStudentKpiRecordsAnalyticsRoute
  '/kpi/target/edit': typeof AuthStudentKpiTargetEditRoute
  '/kpi/academics/': typeof AuthStudentKpiAcademicsIndexRoute
  '/kpi/records/': typeof AuthStudentKpiRecordsIndexRoute
  '/kpi/target/': typeof AuthStudentKpiTargetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/user-sessions': typeof AuthSettingsUserSessionsRoute
  '/mentorships/dashboard': typeof AuthLecturerMentorshipsDashboardRoute
  '/mentorships/students': typeof AuthLecturerMentorshipsStudentsRoute
  '/staff/intakes': typeof AuthStaffStaffIntakesRoute
  '/staff/manage-lecturers': typeof AuthStaffStaffManageLecturersRoute
  '/staff/manage-students': typeof AuthStaffStaffManageStudentsRoute
  '/kpi/challenges': typeof AuthStudentKpiChallengesRoute
  '/kpi/overview': typeof AuthStudentKpiOverviewRoute
  '/kpi/academics/analytics': typeof AuthStudentKpiAcademicsAnalyticsRoute
  '/kpi/records/analytics': typeof AuthStudentKpiRecordsAnalyticsRoute
  '/kpi/target/edit': typeof AuthStudentKpiTargetEditRoute
  '/kpi/academics': typeof AuthStudentKpiAcademicsIndexRoute
  '/kpi/records': typeof AuthStudentKpiRecordsIndexRoute
  '/kpi/target': typeof AuthStudentKpiTargetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_auth/_lecturer': typeof AuthLecturerRouteRouteWithChildren
  '/_auth/_staff': typeof AuthStaffRouteRouteWithChildren
  '/_auth/_student': typeof AuthStudentRouteRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/user-sessions': typeof AuthSettingsUserSessionsRoute
  '/_auth/_student/kpi/academics': typeof AuthStudentKpiAcademicsRouteRouteWithChildren
  '/_auth/_student/kpi/records': typeof AuthStudentKpiRecordsRouteRouteWithChildren
  '/_auth/_student/kpi/target': typeof AuthStudentKpiTargetRouteRouteWithChildren
  '/_auth/_lecturer/mentorships/dashboard': typeof AuthLecturerMentorshipsDashboardRoute
  '/_auth/_lecturer/mentorships/students': typeof AuthLecturerMentorshipsStudentsRoute
  '/_auth/_staff/staff/intakes': typeof AuthStaffStaffIntakesRoute
  '/_auth/_staff/staff/manage-lecturers': typeof AuthStaffStaffManageLecturersRoute
  '/_auth/_staff/staff/manage-students': typeof AuthStaffStaffManageStudentsRoute
  '/_auth/_student/kpi/challenges': typeof AuthStudentKpiChallengesRoute
  '/_auth/_student/kpi/overview': typeof AuthStudentKpiOverviewRoute
  '/_auth/_student/kpi/academics/analytics': typeof AuthStudentKpiAcademicsAnalyticsRoute
  '/_auth/_student/kpi/records/analytics': typeof AuthStudentKpiRecordsAnalyticsRoute
  '/_auth/_student/kpi/target/edit': typeof AuthStudentKpiTargetEditRoute
  '/_auth/_student/kpi/academics/': typeof AuthStudentKpiAcademicsIndexRoute
  '/_auth/_student/kpi/records/': typeof AuthStudentKpiRecordsIndexRoute
  '/_auth/_student/kpi/target/': typeof AuthStudentKpiTargetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/settings/profile'
    | '/settings/user-sessions'
    | '/kpi/academics'
    | '/kpi/records'
    | '/kpi/target'
    | '/mentorships/dashboard'
    | '/mentorships/students'
    | '/staff/intakes'
    | '/staff/manage-lecturers'
    | '/staff/manage-students'
    | '/kpi/challenges'
    | '/kpi/overview'
    | '/kpi/academics/analytics'
    | '/kpi/records/analytics'
    | '/kpi/target/edit'
    | '/kpi/academics/'
    | '/kpi/records/'
    | '/kpi/target/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/settings/profile'
    | '/settings/user-sessions'
    | '/mentorships/dashboard'
    | '/mentorships/students'
    | '/staff/intakes'
    | '/staff/manage-lecturers'
    | '/staff/manage-students'
    | '/kpi/challenges'
    | '/kpi/overview'
    | '/kpi/academics/analytics'
    | '/kpi/records/analytics'
    | '/kpi/target/edit'
    | '/kpi/academics'
    | '/kpi/records'
    | '/kpi/target'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_auth/_lecturer'
    | '/_auth/_staff'
    | '/_auth/_student'
    | '/_auth/settings'
    | '/_auth/dashboard'
    | '/_public/login'
    | '/_public/register'
    | '/_auth/settings/profile'
    | '/_auth/settings/user-sessions'
    | '/_auth/_student/kpi/academics'
    | '/_auth/_student/kpi/records'
    | '/_auth/_student/kpi/target'
    | '/_auth/_lecturer/mentorships/dashboard'
    | '/_auth/_lecturer/mentorships/students'
    | '/_auth/_staff/staff/intakes'
    | '/_auth/_staff/staff/manage-lecturers'
    | '/_auth/_staff/staff/manage-students'
    | '/_auth/_student/kpi/challenges'
    | '/_auth/_student/kpi/overview'
    | '/_auth/_student/kpi/academics/analytics'
    | '/_auth/_student/kpi/records/analytics'
    | '/_auth/_student/kpi/target/edit'
    | '/_auth/_student/kpi/academics/'
    | '/_auth/_student/kpi/records/'
    | '/_auth/_student/kpi/target/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_student': {
      id: '/_auth/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthStudentRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_staff': {
      id: '/_auth/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthStaffRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_lecturer': {
      id: '/_auth/_lecturer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLecturerRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/user-sessions': {
      id: '/_auth/settings/user-sessions'
      path: '/user-sessions'
      fullPath: '/settings/user-sessions'
      preLoaderRoute: typeof AuthSettingsUserSessionsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/_student/kpi/overview': {
      id: '/_auth/_student/kpi/overview'
      path: '/kpi/overview'
      fullPath: '/kpi/overview'
      preLoaderRoute: typeof AuthStudentKpiOverviewRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_student/kpi/challenges': {
      id: '/_auth/_student/kpi/challenges'
      path: '/kpi/challenges'
      fullPath: '/kpi/challenges'
      preLoaderRoute: typeof AuthStudentKpiChallengesRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_staff/staff/manage-students': {
      id: '/_auth/_staff/staff/manage-students'
      path: '/staff/manage-students'
      fullPath: '/staff/manage-students'
      preLoaderRoute: typeof AuthStaffStaffManageStudentsRouteImport
      parentRoute: typeof AuthStaffRouteRoute
    }
    '/_auth/_staff/staff/manage-lecturers': {
      id: '/_auth/_staff/staff/manage-lecturers'
      path: '/staff/manage-lecturers'
      fullPath: '/staff/manage-lecturers'
      preLoaderRoute: typeof AuthStaffStaffManageLecturersRouteImport
      parentRoute: typeof AuthStaffRouteRoute
    }
    '/_auth/_staff/staff/intakes': {
      id: '/_auth/_staff/staff/intakes'
      path: '/staff/intakes'
      fullPath: '/staff/intakes'
      preLoaderRoute: typeof AuthStaffStaffIntakesRouteImport
      parentRoute: typeof AuthStaffRouteRoute
    }
    '/_auth/_lecturer/mentorships/students': {
      id: '/_auth/_lecturer/mentorships/students'
      path: '/mentorships/students'
      fullPath: '/mentorships/students'
      preLoaderRoute: typeof AuthLecturerMentorshipsStudentsRouteImport
      parentRoute: typeof AuthLecturerRouteRoute
    }
    '/_auth/_lecturer/mentorships/dashboard': {
      id: '/_auth/_lecturer/mentorships/dashboard'
      path: '/mentorships/dashboard'
      fullPath: '/mentorships/dashboard'
      preLoaderRoute: typeof AuthLecturerMentorshipsDashboardRouteImport
      parentRoute: typeof AuthLecturerRouteRoute
    }
    '/_auth/_student/kpi/target': {
      id: '/_auth/_student/kpi/target'
      path: '/kpi/target'
      fullPath: '/kpi/target'
      preLoaderRoute: typeof AuthStudentKpiTargetRouteRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_student/kpi/records': {
      id: '/_auth/_student/kpi/records'
      path: '/kpi/records'
      fullPath: '/kpi/records'
      preLoaderRoute: typeof AuthStudentKpiRecordsRouteRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_student/kpi/academics': {
      id: '/_auth/_student/kpi/academics'
      path: '/kpi/academics'
      fullPath: '/kpi/academics'
      preLoaderRoute: typeof AuthStudentKpiAcademicsRouteRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_student/kpi/target/': {
      id: '/_auth/_student/kpi/target/'
      path: '/'
      fullPath: '/kpi/target/'
      preLoaderRoute: typeof AuthStudentKpiTargetIndexRouteImport
      parentRoute: typeof AuthStudentKpiTargetRouteRoute
    }
    '/_auth/_student/kpi/records/': {
      id: '/_auth/_student/kpi/records/'
      path: '/'
      fullPath: '/kpi/records/'
      preLoaderRoute: typeof AuthStudentKpiRecordsIndexRouteImport
      parentRoute: typeof AuthStudentKpiRecordsRouteRoute
    }
    '/_auth/_student/kpi/academics/': {
      id: '/_auth/_student/kpi/academics/'
      path: '/'
      fullPath: '/kpi/academics/'
      preLoaderRoute: typeof AuthStudentKpiAcademicsIndexRouteImport
      parentRoute: typeof AuthStudentKpiAcademicsRouteRoute
    }
    '/_auth/_student/kpi/target/edit': {
      id: '/_auth/_student/kpi/target/edit'
      path: '/edit'
      fullPath: '/kpi/target/edit'
      preLoaderRoute: typeof AuthStudentKpiTargetEditRouteImport
      parentRoute: typeof AuthStudentKpiTargetRouteRoute
    }
    '/_auth/_student/kpi/records/analytics': {
      id: '/_auth/_student/kpi/records/analytics'
      path: '/analytics'
      fullPath: '/kpi/records/analytics'
      preLoaderRoute: typeof AuthStudentKpiRecordsAnalyticsRouteImport
      parentRoute: typeof AuthStudentKpiRecordsRouteRoute
    }
    '/_auth/_student/kpi/academics/analytics': {
      id: '/_auth/_student/kpi/academics/analytics'
      path: '/analytics'
      fullPath: '/kpi/academics/analytics'
      preLoaderRoute: typeof AuthStudentKpiAcademicsAnalyticsRouteImport
      parentRoute: typeof AuthStudentKpiAcademicsRouteRoute
    }
  }
}

interface AuthLecturerRouteRouteChildren {
  AuthLecturerMentorshipsDashboardRoute: typeof AuthLecturerMentorshipsDashboardRoute
  AuthLecturerMentorshipsStudentsRoute: typeof AuthLecturerMentorshipsStudentsRoute
}

const AuthLecturerRouteRouteChildren: AuthLecturerRouteRouteChildren = {
  AuthLecturerMentorshipsDashboardRoute: AuthLecturerMentorshipsDashboardRoute,
  AuthLecturerMentorshipsStudentsRoute: AuthLecturerMentorshipsStudentsRoute,
}

const AuthLecturerRouteRouteWithChildren =
  AuthLecturerRouteRoute._addFileChildren(AuthLecturerRouteRouteChildren)

interface AuthStaffRouteRouteChildren {
  AuthStaffStaffIntakesRoute: typeof AuthStaffStaffIntakesRoute
  AuthStaffStaffManageLecturersRoute: typeof AuthStaffStaffManageLecturersRoute
  AuthStaffStaffManageStudentsRoute: typeof AuthStaffStaffManageStudentsRoute
}

const AuthStaffRouteRouteChildren: AuthStaffRouteRouteChildren = {
  AuthStaffStaffIntakesRoute: AuthStaffStaffIntakesRoute,
  AuthStaffStaffManageLecturersRoute: AuthStaffStaffManageLecturersRoute,
  AuthStaffStaffManageStudentsRoute: AuthStaffStaffManageStudentsRoute,
}

const AuthStaffRouteRouteWithChildren = AuthStaffRouteRoute._addFileChildren(
  AuthStaffRouteRouteChildren,
)

interface AuthStudentKpiAcademicsRouteRouteChildren {
  AuthStudentKpiAcademicsAnalyticsRoute: typeof AuthStudentKpiAcademicsAnalyticsRoute
  AuthStudentKpiAcademicsIndexRoute: typeof AuthStudentKpiAcademicsIndexRoute
}

const AuthStudentKpiAcademicsRouteRouteChildren: AuthStudentKpiAcademicsRouteRouteChildren =
  {
    AuthStudentKpiAcademicsAnalyticsRoute:
      AuthStudentKpiAcademicsAnalyticsRoute,
    AuthStudentKpiAcademicsIndexRoute: AuthStudentKpiAcademicsIndexRoute,
  }

const AuthStudentKpiAcademicsRouteRouteWithChildren =
  AuthStudentKpiAcademicsRouteRoute._addFileChildren(
    AuthStudentKpiAcademicsRouteRouteChildren,
  )

interface AuthStudentKpiRecordsRouteRouteChildren {
  AuthStudentKpiRecordsAnalyticsRoute: typeof AuthStudentKpiRecordsAnalyticsRoute
  AuthStudentKpiRecordsIndexRoute: typeof AuthStudentKpiRecordsIndexRoute
}

const AuthStudentKpiRecordsRouteRouteChildren: AuthStudentKpiRecordsRouteRouteChildren =
  {
    AuthStudentKpiRecordsAnalyticsRoute: AuthStudentKpiRecordsAnalyticsRoute,
    AuthStudentKpiRecordsIndexRoute: AuthStudentKpiRecordsIndexRoute,
  }

const AuthStudentKpiRecordsRouteRouteWithChildren =
  AuthStudentKpiRecordsRouteRoute._addFileChildren(
    AuthStudentKpiRecordsRouteRouteChildren,
  )

interface AuthStudentKpiTargetRouteRouteChildren {
  AuthStudentKpiTargetEditRoute: typeof AuthStudentKpiTargetEditRoute
  AuthStudentKpiTargetIndexRoute: typeof AuthStudentKpiTargetIndexRoute
}

const AuthStudentKpiTargetRouteRouteChildren: AuthStudentKpiTargetRouteRouteChildren =
  {
    AuthStudentKpiTargetEditRoute: AuthStudentKpiTargetEditRoute,
    AuthStudentKpiTargetIndexRoute: AuthStudentKpiTargetIndexRoute,
  }

const AuthStudentKpiTargetRouteRouteWithChildren =
  AuthStudentKpiTargetRouteRoute._addFileChildren(
    AuthStudentKpiTargetRouteRouteChildren,
  )

interface AuthStudentRouteRouteChildren {
  AuthStudentKpiAcademicsRouteRoute: typeof AuthStudentKpiAcademicsRouteRouteWithChildren
  AuthStudentKpiRecordsRouteRoute: typeof AuthStudentKpiRecordsRouteRouteWithChildren
  AuthStudentKpiTargetRouteRoute: typeof AuthStudentKpiTargetRouteRouteWithChildren
  AuthStudentKpiChallengesRoute: typeof AuthStudentKpiChallengesRoute
  AuthStudentKpiOverviewRoute: typeof AuthStudentKpiOverviewRoute
}

const AuthStudentRouteRouteChildren: AuthStudentRouteRouteChildren = {
  AuthStudentKpiAcademicsRouteRoute:
    AuthStudentKpiAcademicsRouteRouteWithChildren,
  AuthStudentKpiRecordsRouteRoute: AuthStudentKpiRecordsRouteRouteWithChildren,
  AuthStudentKpiTargetRouteRoute: AuthStudentKpiTargetRouteRouteWithChildren,
  AuthStudentKpiChallengesRoute: AuthStudentKpiChallengesRoute,
  AuthStudentKpiOverviewRoute: AuthStudentKpiOverviewRoute,
}

const AuthStudentRouteRouteWithChildren =
  AuthStudentRouteRoute._addFileChildren(AuthStudentRouteRouteChildren)

interface AuthSettingsRouteRouteChildren {
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsUserSessionsRoute: typeof AuthSettingsUserSessionsRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsUserSessionsRoute: AuthSettingsUserSessionsRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthLecturerRouteRoute: typeof AuthLecturerRouteRouteWithChildren
  AuthStaffRouteRoute: typeof AuthStaffRouteRouteWithChildren
  AuthStudentRouteRoute: typeof AuthStudentRouteRouteWithChildren
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLecturerRouteRoute: AuthLecturerRouteRouteWithChildren,
  AuthStaffRouteRoute: AuthStaffRouteRouteWithChildren,
  AuthStudentRouteRoute: AuthStudentRouteRouteWithChildren,
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
