/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthSettingsRouteRouteImport } from './routes/_auth/settings/route'
import { Route as AuthStudentRouteRouteImport } from './routes/_auth/_student/route'
import { Route as AuthStaffRouteRouteImport } from './routes/_auth/_staff/route'
import { Route as AuthLecturerRouteRouteImport } from './routes/_auth/_lecturer/route'
import { Route as AuthSettingsUserSessionsRouteImport } from './routes/_auth/settings/user-sessions'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthLecturerMentorshipRouteRouteImport } from './routes/_auth/_lecturer/mentorship/route'
import { Route as AuthLecturerMentorshipIndexRouteImport } from './routes/_auth/_lecturer/mentorship/index'
import { Route as AuthStudentKpiOverviewRouteImport } from './routes/_auth/_student/kpi/overview'
import { Route as AuthStudentKpiChallengesRouteImport } from './routes/_auth/_student/kpi/challenges'
import { Route as AuthStaffStaffManageLecturersRouteImport } from './routes/_auth/_staff/staff/manage-lecturers'
import { Route as AuthLecturerMentorshipStudentsRouteImport } from './routes/_auth/_lecturer/mentorship/students'
import { Route as AuthLecturerMentorshipAssignRouteImport } from './routes/_auth/_lecturer/mentorship/assign'
import { Route as AuthLecturerMentorshipMentorshipIdRouteImport } from './routes/_auth/_lecturer/mentorship/$mentorshipId'
import { Route as AuthStudentKpiTargetRouteRouteImport } from './routes/_auth/_student/kpi/target/route'
import { Route as AuthStudentKpiRecordsRouteRouteImport } from './routes/_auth/_student/kpi/records/route'
import { Route as AuthStudentKpiAcademicsRouteRouteImport } from './routes/_auth/_student/kpi/academics/route'
import { Route as AuthStaffStaffStudentsRouteRouteImport } from './routes/_auth/_staff/staff/students/route'
import { Route as AuthStaffStaffMentorshipsRouteRouteImport } from './routes/_auth/_staff/staff/mentorships/route'
import { Route as AuthStaffStaffIntakeRouteRouteImport } from './routes/_auth/_staff/staff/intake/route'
import { Route as AuthStudentKpiTargetIndexRouteImport } from './routes/_auth/_student/kpi/target/index'
import { Route as AuthStudentKpiRecordsIndexRouteImport } from './routes/_auth/_student/kpi/records/index'
import { Route as AuthStudentKpiAcademicsIndexRouteImport } from './routes/_auth/_student/kpi/academics/index'
import { Route as AuthStaffStaffStudentsIndexRouteImport } from './routes/_auth/_staff/staff/students/index'
import { Route as AuthStaffStaffMentorshipsIndexRouteImport } from './routes/_auth/_staff/staff/mentorships/index'
import { Route as AuthStaffStaffIntakeIndexRouteImport } from './routes/_auth/_staff/staff/intake/index'
import { Route as AuthStudentKpiTargetEditRouteImport } from './routes/_auth/_student/kpi/target/edit'
import { Route as AuthStudentKpiRecordsAnalyticsRouteImport } from './routes/_auth/_student/kpi/records/analytics'
import { Route as AuthStudentKpiAcademicsAnalyticsRouteImport } from './routes/_auth/_student/kpi/academics/analytics'
import { Route as AuthStaffStaffMentorshipsAssignRouteImport } from './routes/_auth/_staff/staff/mentorships/assign'
import { Route as AuthStaffStaffMentorshipsMentorshipIdRouteImport } from './routes/_auth/_staff/staff/mentorships/$mentorshipId'
import { Route as AuthStaffStaffIntakeAssignKpiRouteImport } from './routes/_auth/_staff/staff/intake/assign-kpi'
import { Route as AuthStaffStaffStudentsIdRouteRouteImport } from './routes/_auth/_staff/staff/students/$id/route'
import { Route as AuthLecturerMentorshipStudentsIdRouteRouteImport } from './routes/_auth/_lecturer/mentorship/students/$id/route'
import { Route as AuthStaffStaffStudentsIdIndexRouteImport } from './routes/_auth/_staff/staff/students/$id/index'
import { Route as AuthLecturerMentorshipStudentsIdIndexRouteImport } from './routes/_auth/_lecturer/mentorship/students/$id/index'
import { Route as AuthStaffStaffStudentsIdKpiTargetRouteImport } from './routes/_auth/_staff/staff/students/$id/kpi-target'
import { Route as AuthStaffStaffStudentsIdKpiRecordsRouteImport } from './routes/_auth/_staff/staff/students/$id/kpi-records'
import { Route as AuthStaffStaffStudentsIdChallengesRouteImport } from './routes/_auth/_staff/staff/students/$id/challenges'
import { Route as AuthStaffStaffStudentsIdAcademicsRouteImport } from './routes/_auth/_staff/staff/students/$id/academics'
import { Route as AuthLecturerMentorshipStudentsIdKpiTargetRouteImport } from './routes/_auth/_lecturer/mentorship/students/$id/kpi-target'
import { Route as AuthLecturerMentorshipStudentsIdKpiRecordsRouteImport } from './routes/_auth/_lecturer/mentorship/students/$id/kpi-records'
import { Route as AuthLecturerMentorshipStudentsIdChallengesRouteImport } from './routes/_auth/_lecturer/mentorship/students/$id/challenges'
import { Route as AuthLecturerMentorshipStudentsIdAcademicsRouteImport } from './routes/_auth/_lecturer/mentorship/students/$id/academics'
import { Route as AuthStaffStaffMentorshipsStudentsIdRouteRouteImport } from './routes/_auth/_staff/staff/mentorships/students/$id/route'
import { Route as AuthStaffStaffMentorshipsStudentsIdIndexRouteImport } from './routes/_auth/_staff/staff/mentorships/students/$id/index'
import { Route as AuthLecturerMentorshipStudentsIdKpiTargetIndexRouteImport } from './routes/_auth/_lecturer/mentorship/students/$id/kpi-target.index'
import { Route as AuthStaffStaffMentorshipsStudentsIdKpiTargetRouteImport } from './routes/_auth/_staff/staff/mentorships/students/$id/kpi-target'
import { Route as AuthStaffStaffMentorshipsStudentsIdKpiRecordsRouteImport } from './routes/_auth/_staff/staff/mentorships/students/$id/kpi-records'
import { Route as AuthStaffStaffMentorshipsStudentsIdChallengesRouteImport } from './routes/_auth/_staff/staff/mentorships/students/$id/challenges'
import { Route as AuthStaffStaffMentorshipsStudentsIdAcademicsRouteImport } from './routes/_auth/_staff/staff/mentorships/students/$id/academics'
import { Route as AuthLecturerMentorshipStudentsIdKpiTargetAssignRouteImport } from './routes/_auth/_lecturer/mentorship/students/$id/kpi-target.assign'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStudentRouteRoute = AuthStudentRouteRouteImport.update({
  id: '/_student',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthStaffRouteRoute = AuthStaffRouteRouteImport.update({
  id: '/_staff',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLecturerRouteRoute = AuthLecturerRouteRouteImport.update({
  id: '/_lecturer',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsUserSessionsRoute =
  AuthSettingsUserSessionsRouteImport.update({
    id: '/user-sessions',
    path: '/user-sessions',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthLecturerMentorshipRouteRoute =
  AuthLecturerMentorshipRouteRouteImport.update({
    id: '/mentorship',
    path: '/mentorship',
    getParentRoute: () => AuthLecturerRouteRoute,
  } as any)
const AuthLecturerMentorshipIndexRoute =
  AuthLecturerMentorshipIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthLecturerMentorshipRouteRoute,
  } as any)
const AuthStudentKpiOverviewRoute = AuthStudentKpiOverviewRouteImport.update({
  id: '/kpi/overview',
  path: '/kpi/overview',
  getParentRoute: () => AuthStudentRouteRoute,
} as any)
const AuthStudentKpiChallengesRoute =
  AuthStudentKpiChallengesRouteImport.update({
    id: '/kpi/challenges',
    path: '/kpi/challenges',
    getParentRoute: () => AuthStudentRouteRoute,
  } as any)
const AuthStaffStaffManageLecturersRoute =
  AuthStaffStaffManageLecturersRouteImport.update({
    id: '/staff/manage-lecturers',
    path: '/staff/manage-lecturers',
    getParentRoute: () => AuthStaffRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsRoute =
  AuthLecturerMentorshipStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthLecturerMentorshipRouteRoute,
  } as any)
const AuthLecturerMentorshipAssignRoute =
  AuthLecturerMentorshipAssignRouteImport.update({
    id: '/assign',
    path: '/assign',
    getParentRoute: () => AuthLecturerMentorshipRouteRoute,
  } as any)
const AuthLecturerMentorshipMentorshipIdRoute =
  AuthLecturerMentorshipMentorshipIdRouteImport.update({
    id: '/$mentorshipId',
    path: '/$mentorshipId',
    getParentRoute: () => AuthLecturerMentorshipRouteRoute,
  } as any)
const AuthStudentKpiTargetRouteRoute =
  AuthStudentKpiTargetRouteRouteImport.update({
    id: '/kpi/target',
    path: '/kpi/target',
    getParentRoute: () => AuthStudentRouteRoute,
  } as any)
const AuthStudentKpiRecordsRouteRoute =
  AuthStudentKpiRecordsRouteRouteImport.update({
    id: '/kpi/records',
    path: '/kpi/records',
    getParentRoute: () => AuthStudentRouteRoute,
  } as any)
const AuthStudentKpiAcademicsRouteRoute =
  AuthStudentKpiAcademicsRouteRouteImport.update({
    id: '/kpi/academics',
    path: '/kpi/academics',
    getParentRoute: () => AuthStudentRouteRoute,
  } as any)
const AuthStaffStaffStudentsRouteRoute =
  AuthStaffStaffStudentsRouteRouteImport.update({
    id: '/staff/students',
    path: '/staff/students',
    getParentRoute: () => AuthStaffRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsRouteRoute =
  AuthStaffStaffMentorshipsRouteRouteImport.update({
    id: '/staff/mentorships',
    path: '/staff/mentorships',
    getParentRoute: () => AuthStaffRouteRoute,
  } as any)
const AuthStaffStaffIntakeRouteRoute =
  AuthStaffStaffIntakeRouteRouteImport.update({
    id: '/staff/intake',
    path: '/staff/intake',
    getParentRoute: () => AuthStaffRouteRoute,
  } as any)
const AuthStudentKpiTargetIndexRoute =
  AuthStudentKpiTargetIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStudentKpiTargetRouteRoute,
  } as any)
const AuthStudentKpiRecordsIndexRoute =
  AuthStudentKpiRecordsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStudentKpiRecordsRouteRoute,
  } as any)
const AuthStudentKpiAcademicsIndexRoute =
  AuthStudentKpiAcademicsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStudentKpiAcademicsRouteRoute,
  } as any)
const AuthStaffStaffStudentsIndexRoute =
  AuthStaffStaffStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStaffStaffStudentsRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsIndexRoute =
  AuthStaffStaffMentorshipsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStaffStaffMentorshipsRouteRoute,
  } as any)
const AuthStaffStaffIntakeIndexRoute =
  AuthStaffStaffIntakeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStaffStaffIntakeRouteRoute,
  } as any)
const AuthStudentKpiTargetEditRoute =
  AuthStudentKpiTargetEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthStudentKpiTargetRouteRoute,
  } as any)
const AuthStudentKpiRecordsAnalyticsRoute =
  AuthStudentKpiRecordsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthStudentKpiRecordsRouteRoute,
  } as any)
const AuthStudentKpiAcademicsAnalyticsRoute =
  AuthStudentKpiAcademicsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthStudentKpiAcademicsRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsAssignRoute =
  AuthStaffStaffMentorshipsAssignRouteImport.update({
    id: '/assign',
    path: '/assign',
    getParentRoute: () => AuthStaffStaffMentorshipsRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsMentorshipIdRoute =
  AuthStaffStaffMentorshipsMentorshipIdRouteImport.update({
    id: '/$mentorshipId',
    path: '/$mentorshipId',
    getParentRoute: () => AuthStaffStaffMentorshipsRouteRoute,
  } as any)
const AuthStaffStaffIntakeAssignKpiRoute =
  AuthStaffStaffIntakeAssignKpiRouteImport.update({
    id: '/assign-kpi',
    path: '/assign-kpi',
    getParentRoute: () => AuthStaffStaffIntakeRouteRoute,
  } as any)
const AuthStaffStaffStudentsIdRouteRoute =
  AuthStaffStaffStudentsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthStaffStaffStudentsRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsIdRouteRoute =
  AuthLecturerMentorshipStudentsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthLecturerMentorshipStudentsRoute,
  } as any)
const AuthStaffStaffStudentsIdIndexRoute =
  AuthStaffStaffStudentsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStaffStaffStudentsIdRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsIdIndexRoute =
  AuthLecturerMentorshipStudentsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthLecturerMentorshipStudentsIdRouteRoute,
  } as any)
const AuthStaffStaffStudentsIdKpiTargetRoute =
  AuthStaffStaffStudentsIdKpiTargetRouteImport.update({
    id: '/kpi-target',
    path: '/kpi-target',
    getParentRoute: () => AuthStaffStaffStudentsIdRouteRoute,
  } as any)
const AuthStaffStaffStudentsIdKpiRecordsRoute =
  AuthStaffStaffStudentsIdKpiRecordsRouteImport.update({
    id: '/kpi-records',
    path: '/kpi-records',
    getParentRoute: () => AuthStaffStaffStudentsIdRouteRoute,
  } as any)
const AuthStaffStaffStudentsIdChallengesRoute =
  AuthStaffStaffStudentsIdChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthStaffStaffStudentsIdRouteRoute,
  } as any)
const AuthStaffStaffStudentsIdAcademicsRoute =
  AuthStaffStaffStudentsIdAcademicsRouteImport.update({
    id: '/academics',
    path: '/academics',
    getParentRoute: () => AuthStaffStaffStudentsIdRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsIdKpiTargetRoute =
  AuthLecturerMentorshipStudentsIdKpiTargetRouteImport.update({
    id: '/kpi-target',
    path: '/kpi-target',
    getParentRoute: () => AuthLecturerMentorshipStudentsIdRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsIdKpiRecordsRoute =
  AuthLecturerMentorshipStudentsIdKpiRecordsRouteImport.update({
    id: '/kpi-records',
    path: '/kpi-records',
    getParentRoute: () => AuthLecturerMentorshipStudentsIdRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsIdChallengesRoute =
  AuthLecturerMentorshipStudentsIdChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthLecturerMentorshipStudentsIdRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsIdAcademicsRoute =
  AuthLecturerMentorshipStudentsIdAcademicsRouteImport.update({
    id: '/academics',
    path: '/academics',
    getParentRoute: () => AuthLecturerMentorshipStudentsIdRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsStudentsIdRouteRoute =
  AuthStaffStaffMentorshipsStudentsIdRouteRouteImport.update({
    id: '/students/$id',
    path: '/students/$id',
    getParentRoute: () => AuthStaffStaffMentorshipsRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsStudentsIdIndexRoute =
  AuthStaffStaffMentorshipsStudentsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStaffStaffMentorshipsStudentsIdRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsIdKpiTargetIndexRoute =
  AuthLecturerMentorshipStudentsIdKpiTargetIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthLecturerMentorshipStudentsIdKpiTargetRoute,
  } as any)
const AuthStaffStaffMentorshipsStudentsIdKpiTargetRoute =
  AuthStaffStaffMentorshipsStudentsIdKpiTargetRouteImport.update({
    id: '/kpi-target',
    path: '/kpi-target',
    getParentRoute: () => AuthStaffStaffMentorshipsStudentsIdRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsStudentsIdKpiRecordsRoute =
  AuthStaffStaffMentorshipsStudentsIdKpiRecordsRouteImport.update({
    id: '/kpi-records',
    path: '/kpi-records',
    getParentRoute: () => AuthStaffStaffMentorshipsStudentsIdRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsStudentsIdChallengesRoute =
  AuthStaffStaffMentorshipsStudentsIdChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthStaffStaffMentorshipsStudentsIdRouteRoute,
  } as any)
const AuthStaffStaffMentorshipsStudentsIdAcademicsRoute =
  AuthStaffStaffMentorshipsStudentsIdAcademicsRouteImport.update({
    id: '/academics',
    path: '/academics',
    getParentRoute: () => AuthStaffStaffMentorshipsStudentsIdRouteRoute,
  } as any)
const AuthLecturerMentorshipStudentsIdKpiTargetAssignRoute =
  AuthLecturerMentorshipStudentsIdKpiTargetAssignRouteImport.update({
    id: '/assign',
    path: '/assign',
    getParentRoute: () => AuthLecturerMentorshipStudentsIdKpiTargetRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/mentorship': typeof AuthLecturerMentorshipRouteRouteWithChildren
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/user-sessions': typeof AuthSettingsUserSessionsRoute
  '/staff/intake': typeof AuthStaffStaffIntakeRouteRouteWithChildren
  '/staff/mentorships': typeof AuthStaffStaffMentorshipsRouteRouteWithChildren
  '/staff/students': typeof AuthStaffStaffStudentsRouteRouteWithChildren
  '/kpi/academics': typeof AuthStudentKpiAcademicsRouteRouteWithChildren
  '/kpi/records': typeof AuthStudentKpiRecordsRouteRouteWithChildren
  '/kpi/target': typeof AuthStudentKpiTargetRouteRouteWithChildren
  '/mentorship/$mentorshipId': typeof AuthLecturerMentorshipMentorshipIdRoute
  '/mentorship/assign': typeof AuthLecturerMentorshipAssignRoute
  '/mentorship/students': typeof AuthLecturerMentorshipStudentsRouteWithChildren
  '/staff/manage-lecturers': typeof AuthStaffStaffManageLecturersRoute
  '/kpi/challenges': typeof AuthStudentKpiChallengesRoute
  '/kpi/overview': typeof AuthStudentKpiOverviewRoute
  '/mentorship/': typeof AuthLecturerMentorshipIndexRoute
  '/mentorship/students/$id': typeof AuthLecturerMentorshipStudentsIdRouteRouteWithChildren
  '/staff/students/$id': typeof AuthStaffStaffStudentsIdRouteRouteWithChildren
  '/staff/intake/assign-kpi': typeof AuthStaffStaffIntakeAssignKpiRoute
  '/staff/mentorships/$mentorshipId': typeof AuthStaffStaffMentorshipsMentorshipIdRoute
  '/staff/mentorships/assign': typeof AuthStaffStaffMentorshipsAssignRoute
  '/kpi/academics/analytics': typeof AuthStudentKpiAcademicsAnalyticsRoute
  '/kpi/records/analytics': typeof AuthStudentKpiRecordsAnalyticsRoute
  '/kpi/target/edit': typeof AuthStudentKpiTargetEditRoute
  '/staff/intake/': typeof AuthStaffStaffIntakeIndexRoute
  '/staff/mentorships/': typeof AuthStaffStaffMentorshipsIndexRoute
  '/staff/students/': typeof AuthStaffStaffStudentsIndexRoute
  '/kpi/academics/': typeof AuthStudentKpiAcademicsIndexRoute
  '/kpi/records/': typeof AuthStudentKpiRecordsIndexRoute
  '/kpi/target/': typeof AuthStudentKpiTargetIndexRoute
  '/staff/mentorships/students/$id': typeof AuthStaffStaffMentorshipsStudentsIdRouteRouteWithChildren
  '/mentorship/students/$id/academics': typeof AuthLecturerMentorshipStudentsIdAcademicsRoute
  '/mentorship/students/$id/challenges': typeof AuthLecturerMentorshipStudentsIdChallengesRoute
  '/mentorship/students/$id/kpi-records': typeof AuthLecturerMentorshipStudentsIdKpiRecordsRoute
  '/mentorship/students/$id/kpi-target': typeof AuthLecturerMentorshipStudentsIdKpiTargetRouteWithChildren
  '/staff/students/$id/academics': typeof AuthStaffStaffStudentsIdAcademicsRoute
  '/staff/students/$id/challenges': typeof AuthStaffStaffStudentsIdChallengesRoute
  '/staff/students/$id/kpi-records': typeof AuthStaffStaffStudentsIdKpiRecordsRoute
  '/staff/students/$id/kpi-target': typeof AuthStaffStaffStudentsIdKpiTargetRoute
  '/mentorship/students/$id/': typeof AuthLecturerMentorshipStudentsIdIndexRoute
  '/staff/students/$id/': typeof AuthStaffStaffStudentsIdIndexRoute
  '/mentorship/students/$id/kpi-target/assign': typeof AuthLecturerMentorshipStudentsIdKpiTargetAssignRoute
  '/staff/mentorships/students/$id/academics': typeof AuthStaffStaffMentorshipsStudentsIdAcademicsRoute
  '/staff/mentorships/students/$id/challenges': typeof AuthStaffStaffMentorshipsStudentsIdChallengesRoute
  '/staff/mentorships/students/$id/kpi-records': typeof AuthStaffStaffMentorshipsStudentsIdKpiRecordsRoute
  '/staff/mentorships/students/$id/kpi-target': typeof AuthStaffStaffMentorshipsStudentsIdKpiTargetRoute
  '/mentorship/students/$id/kpi-target/': typeof AuthLecturerMentorshipStudentsIdKpiTargetIndexRoute
  '/staff/mentorships/students/$id/': typeof AuthStaffStaffMentorshipsStudentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/user-sessions': typeof AuthSettingsUserSessionsRoute
  '/mentorship/$mentorshipId': typeof AuthLecturerMentorshipMentorshipIdRoute
  '/mentorship/assign': typeof AuthLecturerMentorshipAssignRoute
  '/mentorship/students': typeof AuthLecturerMentorshipStudentsRouteWithChildren
  '/staff/manage-lecturers': typeof AuthStaffStaffManageLecturersRoute
  '/kpi/challenges': typeof AuthStudentKpiChallengesRoute
  '/kpi/overview': typeof AuthStudentKpiOverviewRoute
  '/mentorship': typeof AuthLecturerMentorshipIndexRoute
  '/staff/intake/assign-kpi': typeof AuthStaffStaffIntakeAssignKpiRoute
  '/staff/mentorships/$mentorshipId': typeof AuthStaffStaffMentorshipsMentorshipIdRoute
  '/staff/mentorships/assign': typeof AuthStaffStaffMentorshipsAssignRoute
  '/kpi/academics/analytics': typeof AuthStudentKpiAcademicsAnalyticsRoute
  '/kpi/records/analytics': typeof AuthStudentKpiRecordsAnalyticsRoute
  '/kpi/target/edit': typeof AuthStudentKpiTargetEditRoute
  '/staff/intake': typeof AuthStaffStaffIntakeIndexRoute
  '/staff/mentorships': typeof AuthStaffStaffMentorshipsIndexRoute
  '/staff/students': typeof AuthStaffStaffStudentsIndexRoute
  '/kpi/academics': typeof AuthStudentKpiAcademicsIndexRoute
  '/kpi/records': typeof AuthStudentKpiRecordsIndexRoute
  '/kpi/target': typeof AuthStudentKpiTargetIndexRoute
  '/mentorship/students/$id/academics': typeof AuthLecturerMentorshipStudentsIdAcademicsRoute
  '/mentorship/students/$id/challenges': typeof AuthLecturerMentorshipStudentsIdChallengesRoute
  '/mentorship/students/$id/kpi-records': typeof AuthLecturerMentorshipStudentsIdKpiRecordsRoute
  '/staff/students/$id/academics': typeof AuthStaffStaffStudentsIdAcademicsRoute
  '/staff/students/$id/challenges': typeof AuthStaffStaffStudentsIdChallengesRoute
  '/staff/students/$id/kpi-records': typeof AuthStaffStaffStudentsIdKpiRecordsRoute
  '/staff/students/$id/kpi-target': typeof AuthStaffStaffStudentsIdKpiTargetRoute
  '/mentorship/students/$id': typeof AuthLecturerMentorshipStudentsIdIndexRoute
  '/staff/students/$id': typeof AuthStaffStaffStudentsIdIndexRoute
  '/mentorship/students/$id/kpi-target/assign': typeof AuthLecturerMentorshipStudentsIdKpiTargetAssignRoute
  '/staff/mentorships/students/$id/academics': typeof AuthStaffStaffMentorshipsStudentsIdAcademicsRoute
  '/staff/mentorships/students/$id/challenges': typeof AuthStaffStaffMentorshipsStudentsIdChallengesRoute
  '/staff/mentorships/students/$id/kpi-records': typeof AuthStaffStaffMentorshipsStudentsIdKpiRecordsRoute
  '/staff/mentorships/students/$id/kpi-target': typeof AuthStaffStaffMentorshipsStudentsIdKpiTargetRoute
  '/mentorship/students/$id/kpi-target': typeof AuthLecturerMentorshipStudentsIdKpiTargetIndexRoute
  '/staff/mentorships/students/$id': typeof AuthStaffStaffMentorshipsStudentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_auth/_lecturer': typeof AuthLecturerRouteRouteWithChildren
  '/_auth/_staff': typeof AuthStaffRouteRouteWithChildren
  '/_auth/_student': typeof AuthStudentRouteRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_auth/_lecturer/mentorship': typeof AuthLecturerMentorshipRouteRouteWithChildren
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/user-sessions': typeof AuthSettingsUserSessionsRoute
  '/_auth/_staff/staff/intake': typeof AuthStaffStaffIntakeRouteRouteWithChildren
  '/_auth/_staff/staff/mentorships': typeof AuthStaffStaffMentorshipsRouteRouteWithChildren
  '/_auth/_staff/staff/students': typeof AuthStaffStaffStudentsRouteRouteWithChildren
  '/_auth/_student/kpi/academics': typeof AuthStudentKpiAcademicsRouteRouteWithChildren
  '/_auth/_student/kpi/records': typeof AuthStudentKpiRecordsRouteRouteWithChildren
  '/_auth/_student/kpi/target': typeof AuthStudentKpiTargetRouteRouteWithChildren
  '/_auth/_lecturer/mentorship/$mentorshipId': typeof AuthLecturerMentorshipMentorshipIdRoute
  '/_auth/_lecturer/mentorship/assign': typeof AuthLecturerMentorshipAssignRoute
  '/_auth/_lecturer/mentorship/students': typeof AuthLecturerMentorshipStudentsRouteWithChildren
  '/_auth/_staff/staff/manage-lecturers': typeof AuthStaffStaffManageLecturersRoute
  '/_auth/_student/kpi/challenges': typeof AuthStudentKpiChallengesRoute
  '/_auth/_student/kpi/overview': typeof AuthStudentKpiOverviewRoute
  '/_auth/_lecturer/mentorship/': typeof AuthLecturerMentorshipIndexRoute
  '/_auth/_lecturer/mentorship/students/$id': typeof AuthLecturerMentorshipStudentsIdRouteRouteWithChildren
  '/_auth/_staff/staff/students/$id': typeof AuthStaffStaffStudentsIdRouteRouteWithChildren
  '/_auth/_staff/staff/intake/assign-kpi': typeof AuthStaffStaffIntakeAssignKpiRoute
  '/_auth/_staff/staff/mentorships/$mentorshipId': typeof AuthStaffStaffMentorshipsMentorshipIdRoute
  '/_auth/_staff/staff/mentorships/assign': typeof AuthStaffStaffMentorshipsAssignRoute
  '/_auth/_student/kpi/academics/analytics': typeof AuthStudentKpiAcademicsAnalyticsRoute
  '/_auth/_student/kpi/records/analytics': typeof AuthStudentKpiRecordsAnalyticsRoute
  '/_auth/_student/kpi/target/edit': typeof AuthStudentKpiTargetEditRoute
  '/_auth/_staff/staff/intake/': typeof AuthStaffStaffIntakeIndexRoute
  '/_auth/_staff/staff/mentorships/': typeof AuthStaffStaffMentorshipsIndexRoute
  '/_auth/_staff/staff/students/': typeof AuthStaffStaffStudentsIndexRoute
  '/_auth/_student/kpi/academics/': typeof AuthStudentKpiAcademicsIndexRoute
  '/_auth/_student/kpi/records/': typeof AuthStudentKpiRecordsIndexRoute
  '/_auth/_student/kpi/target/': typeof AuthStudentKpiTargetIndexRoute
  '/_auth/_staff/staff/mentorships/students/$id': typeof AuthStaffStaffMentorshipsStudentsIdRouteRouteWithChildren
  '/_auth/_lecturer/mentorship/students/$id/academics': typeof AuthLecturerMentorshipStudentsIdAcademicsRoute
  '/_auth/_lecturer/mentorship/students/$id/challenges': typeof AuthLecturerMentorshipStudentsIdChallengesRoute
  '/_auth/_lecturer/mentorship/students/$id/kpi-records': typeof AuthLecturerMentorshipStudentsIdKpiRecordsRoute
  '/_auth/_lecturer/mentorship/students/$id/kpi-target': typeof AuthLecturerMentorshipStudentsIdKpiTargetRouteWithChildren
  '/_auth/_staff/staff/students/$id/academics': typeof AuthStaffStaffStudentsIdAcademicsRoute
  '/_auth/_staff/staff/students/$id/challenges': typeof AuthStaffStaffStudentsIdChallengesRoute
  '/_auth/_staff/staff/students/$id/kpi-records': typeof AuthStaffStaffStudentsIdKpiRecordsRoute
  '/_auth/_staff/staff/students/$id/kpi-target': typeof AuthStaffStaffStudentsIdKpiTargetRoute
  '/_auth/_lecturer/mentorship/students/$id/': typeof AuthLecturerMentorshipStudentsIdIndexRoute
  '/_auth/_staff/staff/students/$id/': typeof AuthStaffStaffStudentsIdIndexRoute
  '/_auth/_lecturer/mentorship/students/$id/kpi-target/assign': typeof AuthLecturerMentorshipStudentsIdKpiTargetAssignRoute
  '/_auth/_staff/staff/mentorships/students/$id/academics': typeof AuthStaffStaffMentorshipsStudentsIdAcademicsRoute
  '/_auth/_staff/staff/mentorships/students/$id/challenges': typeof AuthStaffStaffMentorshipsStudentsIdChallengesRoute
  '/_auth/_staff/staff/mentorships/students/$id/kpi-records': typeof AuthStaffStaffMentorshipsStudentsIdKpiRecordsRoute
  '/_auth/_staff/staff/mentorships/students/$id/kpi-target': typeof AuthStaffStaffMentorshipsStudentsIdKpiTargetRoute
  '/_auth/_lecturer/mentorship/students/$id/kpi-target/': typeof AuthLecturerMentorshipStudentsIdKpiTargetIndexRoute
  '/_auth/_staff/staff/mentorships/students/$id/': typeof AuthStaffStaffMentorshipsStudentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/mentorship'
    | '/settings/profile'
    | '/settings/user-sessions'
    | '/staff/intake'
    | '/staff/mentorships'
    | '/staff/students'
    | '/kpi/academics'
    | '/kpi/records'
    | '/kpi/target'
    | '/mentorship/$mentorshipId'
    | '/mentorship/assign'
    | '/mentorship/students'
    | '/staff/manage-lecturers'
    | '/kpi/challenges'
    | '/kpi/overview'
    | '/mentorship/'
    | '/mentorship/students/$id'
    | '/staff/students/$id'
    | '/staff/intake/assign-kpi'
    | '/staff/mentorships/$mentorshipId'
    | '/staff/mentorships/assign'
    | '/kpi/academics/analytics'
    | '/kpi/records/analytics'
    | '/kpi/target/edit'
    | '/staff/intake/'
    | '/staff/mentorships/'
    | '/staff/students/'
    | '/kpi/academics/'
    | '/kpi/records/'
    | '/kpi/target/'
    | '/staff/mentorships/students/$id'
    | '/mentorship/students/$id/academics'
    | '/mentorship/students/$id/challenges'
    | '/mentorship/students/$id/kpi-records'
    | '/mentorship/students/$id/kpi-target'
    | '/staff/students/$id/academics'
    | '/staff/students/$id/challenges'
    | '/staff/students/$id/kpi-records'
    | '/staff/students/$id/kpi-target'
    | '/mentorship/students/$id/'
    | '/staff/students/$id/'
    | '/mentorship/students/$id/kpi-target/assign'
    | '/staff/mentorships/students/$id/academics'
    | '/staff/mentorships/students/$id/challenges'
    | '/staff/mentorships/students/$id/kpi-records'
    | '/staff/mentorships/students/$id/kpi-target'
    | '/mentorship/students/$id/kpi-target/'
    | '/staff/mentorships/students/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/settings/profile'
    | '/settings/user-sessions'
    | '/mentorship/$mentorshipId'
    | '/mentorship/assign'
    | '/mentorship/students'
    | '/staff/manage-lecturers'
    | '/kpi/challenges'
    | '/kpi/overview'
    | '/mentorship'
    | '/staff/intake/assign-kpi'
    | '/staff/mentorships/$mentorshipId'
    | '/staff/mentorships/assign'
    | '/kpi/academics/analytics'
    | '/kpi/records/analytics'
    | '/kpi/target/edit'
    | '/staff/intake'
    | '/staff/mentorships'
    | '/staff/students'
    | '/kpi/academics'
    | '/kpi/records'
    | '/kpi/target'
    | '/mentorship/students/$id/academics'
    | '/mentorship/students/$id/challenges'
    | '/mentorship/students/$id/kpi-records'
    | '/staff/students/$id/academics'
    | '/staff/students/$id/challenges'
    | '/staff/students/$id/kpi-records'
    | '/staff/students/$id/kpi-target'
    | '/mentorship/students/$id'
    | '/staff/students/$id'
    | '/mentorship/students/$id/kpi-target/assign'
    | '/staff/mentorships/students/$id/academics'
    | '/staff/mentorships/students/$id/challenges'
    | '/staff/mentorships/students/$id/kpi-records'
    | '/staff/mentorships/students/$id/kpi-target'
    | '/mentorship/students/$id/kpi-target'
    | '/staff/mentorships/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_auth/_lecturer'
    | '/_auth/_staff'
    | '/_auth/_student'
    | '/_auth/settings'
    | '/_auth/dashboard'
    | '/_public/login'
    | '/_public/register'
    | '/_auth/_lecturer/mentorship'
    | '/_auth/settings/profile'
    | '/_auth/settings/user-sessions'
    | '/_auth/_staff/staff/intake'
    | '/_auth/_staff/staff/mentorships'
    | '/_auth/_staff/staff/students'
    | '/_auth/_student/kpi/academics'
    | '/_auth/_student/kpi/records'
    | '/_auth/_student/kpi/target'
    | '/_auth/_lecturer/mentorship/$mentorshipId'
    | '/_auth/_lecturer/mentorship/assign'
    | '/_auth/_lecturer/mentorship/students'
    | '/_auth/_staff/staff/manage-lecturers'
    | '/_auth/_student/kpi/challenges'
    | '/_auth/_student/kpi/overview'
    | '/_auth/_lecturer/mentorship/'
    | '/_auth/_lecturer/mentorship/students/$id'
    | '/_auth/_staff/staff/students/$id'
    | '/_auth/_staff/staff/intake/assign-kpi'
    | '/_auth/_staff/staff/mentorships/$mentorshipId'
    | '/_auth/_staff/staff/mentorships/assign'
    | '/_auth/_student/kpi/academics/analytics'
    | '/_auth/_student/kpi/records/analytics'
    | '/_auth/_student/kpi/target/edit'
    | '/_auth/_staff/staff/intake/'
    | '/_auth/_staff/staff/mentorships/'
    | '/_auth/_staff/staff/students/'
    | '/_auth/_student/kpi/academics/'
    | '/_auth/_student/kpi/records/'
    | '/_auth/_student/kpi/target/'
    | '/_auth/_staff/staff/mentorships/students/$id'
    | '/_auth/_lecturer/mentorship/students/$id/academics'
    | '/_auth/_lecturer/mentorship/students/$id/challenges'
    | '/_auth/_lecturer/mentorship/students/$id/kpi-records'
    | '/_auth/_lecturer/mentorship/students/$id/kpi-target'
    | '/_auth/_staff/staff/students/$id/academics'
    | '/_auth/_staff/staff/students/$id/challenges'
    | '/_auth/_staff/staff/students/$id/kpi-records'
    | '/_auth/_staff/staff/students/$id/kpi-target'
    | '/_auth/_lecturer/mentorship/students/$id/'
    | '/_auth/_staff/staff/students/$id/'
    | '/_auth/_lecturer/mentorship/students/$id/kpi-target/assign'
    | '/_auth/_staff/staff/mentorships/students/$id/academics'
    | '/_auth/_staff/staff/mentorships/students/$id/challenges'
    | '/_auth/_staff/staff/mentorships/students/$id/kpi-records'
    | '/_auth/_staff/staff/mentorships/students/$id/kpi-target'
    | '/_auth/_lecturer/mentorship/students/$id/kpi-target/'
    | '/_auth/_staff/staff/mentorships/students/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_student': {
      id: '/_auth/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthStudentRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_staff': {
      id: '/_auth/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthStaffRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_lecturer': {
      id: '/_auth/_lecturer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLecturerRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/user-sessions': {
      id: '/_auth/settings/user-sessions'
      path: '/user-sessions'
      fullPath: '/settings/user-sessions'
      preLoaderRoute: typeof AuthSettingsUserSessionsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/_lecturer/mentorship': {
      id: '/_auth/_lecturer/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof AuthLecturerMentorshipRouteRouteImport
      parentRoute: typeof AuthLecturerRouteRoute
    }
    '/_auth/_lecturer/mentorship/': {
      id: '/_auth/_lecturer/mentorship/'
      path: '/'
      fullPath: '/mentorship/'
      preLoaderRoute: typeof AuthLecturerMentorshipIndexRouteImport
      parentRoute: typeof AuthLecturerMentorshipRouteRoute
    }
    '/_auth/_student/kpi/overview': {
      id: '/_auth/_student/kpi/overview'
      path: '/kpi/overview'
      fullPath: '/kpi/overview'
      preLoaderRoute: typeof AuthStudentKpiOverviewRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_student/kpi/challenges': {
      id: '/_auth/_student/kpi/challenges'
      path: '/kpi/challenges'
      fullPath: '/kpi/challenges'
      preLoaderRoute: typeof AuthStudentKpiChallengesRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_staff/staff/manage-lecturers': {
      id: '/_auth/_staff/staff/manage-lecturers'
      path: '/staff/manage-lecturers'
      fullPath: '/staff/manage-lecturers'
      preLoaderRoute: typeof AuthStaffStaffManageLecturersRouteImport
      parentRoute: typeof AuthStaffRouteRoute
    }
    '/_auth/_lecturer/mentorship/students': {
      id: '/_auth/_lecturer/mentorship/students'
      path: '/students'
      fullPath: '/mentorship/students'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsRouteImport
      parentRoute: typeof AuthLecturerMentorshipRouteRoute
    }
    '/_auth/_lecturer/mentorship/assign': {
      id: '/_auth/_lecturer/mentorship/assign'
      path: '/assign'
      fullPath: '/mentorship/assign'
      preLoaderRoute: typeof AuthLecturerMentorshipAssignRouteImport
      parentRoute: typeof AuthLecturerMentorshipRouteRoute
    }
    '/_auth/_lecturer/mentorship/$mentorshipId': {
      id: '/_auth/_lecturer/mentorship/$mentorshipId'
      path: '/$mentorshipId'
      fullPath: '/mentorship/$mentorshipId'
      preLoaderRoute: typeof AuthLecturerMentorshipMentorshipIdRouteImport
      parentRoute: typeof AuthLecturerMentorshipRouteRoute
    }
    '/_auth/_student/kpi/target': {
      id: '/_auth/_student/kpi/target'
      path: '/kpi/target'
      fullPath: '/kpi/target'
      preLoaderRoute: typeof AuthStudentKpiTargetRouteRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_student/kpi/records': {
      id: '/_auth/_student/kpi/records'
      path: '/kpi/records'
      fullPath: '/kpi/records'
      preLoaderRoute: typeof AuthStudentKpiRecordsRouteRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_student/kpi/academics': {
      id: '/_auth/_student/kpi/academics'
      path: '/kpi/academics'
      fullPath: '/kpi/academics'
      preLoaderRoute: typeof AuthStudentKpiAcademicsRouteRouteImport
      parentRoute: typeof AuthStudentRouteRoute
    }
    '/_auth/_staff/staff/students': {
      id: '/_auth/_staff/staff/students'
      path: '/staff/students'
      fullPath: '/staff/students'
      preLoaderRoute: typeof AuthStaffStaffStudentsRouteRouteImport
      parentRoute: typeof AuthStaffRouteRoute
    }
    '/_auth/_staff/staff/mentorships': {
      id: '/_auth/_staff/staff/mentorships'
      path: '/staff/mentorships'
      fullPath: '/staff/mentorships'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsRouteRouteImport
      parentRoute: typeof AuthStaffRouteRoute
    }
    '/_auth/_staff/staff/intake': {
      id: '/_auth/_staff/staff/intake'
      path: '/staff/intake'
      fullPath: '/staff/intake'
      preLoaderRoute: typeof AuthStaffStaffIntakeRouteRouteImport
      parentRoute: typeof AuthStaffRouteRoute
    }
    '/_auth/_student/kpi/target/': {
      id: '/_auth/_student/kpi/target/'
      path: '/'
      fullPath: '/kpi/target/'
      preLoaderRoute: typeof AuthStudentKpiTargetIndexRouteImport
      parentRoute: typeof AuthStudentKpiTargetRouteRoute
    }
    '/_auth/_student/kpi/records/': {
      id: '/_auth/_student/kpi/records/'
      path: '/'
      fullPath: '/kpi/records/'
      preLoaderRoute: typeof AuthStudentKpiRecordsIndexRouteImport
      parentRoute: typeof AuthStudentKpiRecordsRouteRoute
    }
    '/_auth/_student/kpi/academics/': {
      id: '/_auth/_student/kpi/academics/'
      path: '/'
      fullPath: '/kpi/academics/'
      preLoaderRoute: typeof AuthStudentKpiAcademicsIndexRouteImport
      parentRoute: typeof AuthStudentKpiAcademicsRouteRoute
    }
    '/_auth/_staff/staff/students/': {
      id: '/_auth/_staff/staff/students/'
      path: '/'
      fullPath: '/staff/students/'
      preLoaderRoute: typeof AuthStaffStaffStudentsIndexRouteImport
      parentRoute: typeof AuthStaffStaffStudentsRouteRoute
    }
    '/_auth/_staff/staff/mentorships/': {
      id: '/_auth/_staff/staff/mentorships/'
      path: '/'
      fullPath: '/staff/mentorships/'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsIndexRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsRouteRoute
    }
    '/_auth/_staff/staff/intake/': {
      id: '/_auth/_staff/staff/intake/'
      path: '/'
      fullPath: '/staff/intake/'
      preLoaderRoute: typeof AuthStaffStaffIntakeIndexRouteImport
      parentRoute: typeof AuthStaffStaffIntakeRouteRoute
    }
    '/_auth/_student/kpi/target/edit': {
      id: '/_auth/_student/kpi/target/edit'
      path: '/edit'
      fullPath: '/kpi/target/edit'
      preLoaderRoute: typeof AuthStudentKpiTargetEditRouteImport
      parentRoute: typeof AuthStudentKpiTargetRouteRoute
    }
    '/_auth/_student/kpi/records/analytics': {
      id: '/_auth/_student/kpi/records/analytics'
      path: '/analytics'
      fullPath: '/kpi/records/analytics'
      preLoaderRoute: typeof AuthStudentKpiRecordsAnalyticsRouteImport
      parentRoute: typeof AuthStudentKpiRecordsRouteRoute
    }
    '/_auth/_student/kpi/academics/analytics': {
      id: '/_auth/_student/kpi/academics/analytics'
      path: '/analytics'
      fullPath: '/kpi/academics/analytics'
      preLoaderRoute: typeof AuthStudentKpiAcademicsAnalyticsRouteImport
      parentRoute: typeof AuthStudentKpiAcademicsRouteRoute
    }
    '/_auth/_staff/staff/mentorships/assign': {
      id: '/_auth/_staff/staff/mentorships/assign'
      path: '/assign'
      fullPath: '/staff/mentorships/assign'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsAssignRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsRouteRoute
    }
    '/_auth/_staff/staff/mentorships/$mentorshipId': {
      id: '/_auth/_staff/staff/mentorships/$mentorshipId'
      path: '/$mentorshipId'
      fullPath: '/staff/mentorships/$mentorshipId'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsMentorshipIdRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsRouteRoute
    }
    '/_auth/_staff/staff/intake/assign-kpi': {
      id: '/_auth/_staff/staff/intake/assign-kpi'
      path: '/assign-kpi'
      fullPath: '/staff/intake/assign-kpi'
      preLoaderRoute: typeof AuthStaffStaffIntakeAssignKpiRouteImport
      parentRoute: typeof AuthStaffStaffIntakeRouteRoute
    }
    '/_auth/_staff/staff/students/$id': {
      id: '/_auth/_staff/staff/students/$id'
      path: '/$id'
      fullPath: '/staff/students/$id'
      preLoaderRoute: typeof AuthStaffStaffStudentsIdRouteRouteImport
      parentRoute: typeof AuthStaffStaffStudentsRouteRoute
    }
    '/_auth/_lecturer/mentorship/students/$id': {
      id: '/_auth/_lecturer/mentorship/students/$id'
      path: '/$id'
      fullPath: '/mentorship/students/$id'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsIdRouteRouteImport
      parentRoute: typeof AuthLecturerMentorshipStudentsRoute
    }
    '/_auth/_staff/staff/students/$id/': {
      id: '/_auth/_staff/staff/students/$id/'
      path: '/'
      fullPath: '/staff/students/$id/'
      preLoaderRoute: typeof AuthStaffStaffStudentsIdIndexRouteImport
      parentRoute: typeof AuthStaffStaffStudentsIdRouteRoute
    }
    '/_auth/_lecturer/mentorship/students/$id/': {
      id: '/_auth/_lecturer/mentorship/students/$id/'
      path: '/'
      fullPath: '/mentorship/students/$id/'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsIdIndexRouteImport
      parentRoute: typeof AuthLecturerMentorshipStudentsIdRouteRoute
    }
    '/_auth/_staff/staff/students/$id/kpi-target': {
      id: '/_auth/_staff/staff/students/$id/kpi-target'
      path: '/kpi-target'
      fullPath: '/staff/students/$id/kpi-target'
      preLoaderRoute: typeof AuthStaffStaffStudentsIdKpiTargetRouteImport
      parentRoute: typeof AuthStaffStaffStudentsIdRouteRoute
    }
    '/_auth/_staff/staff/students/$id/kpi-records': {
      id: '/_auth/_staff/staff/students/$id/kpi-records'
      path: '/kpi-records'
      fullPath: '/staff/students/$id/kpi-records'
      preLoaderRoute: typeof AuthStaffStaffStudentsIdKpiRecordsRouteImport
      parentRoute: typeof AuthStaffStaffStudentsIdRouteRoute
    }
    '/_auth/_staff/staff/students/$id/challenges': {
      id: '/_auth/_staff/staff/students/$id/challenges'
      path: '/challenges'
      fullPath: '/staff/students/$id/challenges'
      preLoaderRoute: typeof AuthStaffStaffStudentsIdChallengesRouteImport
      parentRoute: typeof AuthStaffStaffStudentsIdRouteRoute
    }
    '/_auth/_staff/staff/students/$id/academics': {
      id: '/_auth/_staff/staff/students/$id/academics'
      path: '/academics'
      fullPath: '/staff/students/$id/academics'
      preLoaderRoute: typeof AuthStaffStaffStudentsIdAcademicsRouteImport
      parentRoute: typeof AuthStaffStaffStudentsIdRouteRoute
    }
    '/_auth/_lecturer/mentorship/students/$id/kpi-target': {
      id: '/_auth/_lecturer/mentorship/students/$id/kpi-target'
      path: '/kpi-target'
      fullPath: '/mentorship/students/$id/kpi-target'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsIdKpiTargetRouteImport
      parentRoute: typeof AuthLecturerMentorshipStudentsIdRouteRoute
    }
    '/_auth/_lecturer/mentorship/students/$id/kpi-records': {
      id: '/_auth/_lecturer/mentorship/students/$id/kpi-records'
      path: '/kpi-records'
      fullPath: '/mentorship/students/$id/kpi-records'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsIdKpiRecordsRouteImport
      parentRoute: typeof AuthLecturerMentorshipStudentsIdRouteRoute
    }
    '/_auth/_lecturer/mentorship/students/$id/challenges': {
      id: '/_auth/_lecturer/mentorship/students/$id/challenges'
      path: '/challenges'
      fullPath: '/mentorship/students/$id/challenges'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsIdChallengesRouteImport
      parentRoute: typeof AuthLecturerMentorshipStudentsIdRouteRoute
    }
    '/_auth/_lecturer/mentorship/students/$id/academics': {
      id: '/_auth/_lecturer/mentorship/students/$id/academics'
      path: '/academics'
      fullPath: '/mentorship/students/$id/academics'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsIdAcademicsRouteImport
      parentRoute: typeof AuthLecturerMentorshipStudentsIdRouteRoute
    }
    '/_auth/_staff/staff/mentorships/students/$id': {
      id: '/_auth/_staff/staff/mentorships/students/$id'
      path: '/students/$id'
      fullPath: '/staff/mentorships/students/$id'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsStudentsIdRouteRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsRouteRoute
    }
    '/_auth/_staff/staff/mentorships/students/$id/': {
      id: '/_auth/_staff/staff/mentorships/students/$id/'
      path: '/'
      fullPath: '/staff/mentorships/students/$id/'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsStudentsIdIndexRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsStudentsIdRouteRoute
    }
    '/_auth/_lecturer/mentorship/students/$id/kpi-target/': {
      id: '/_auth/_lecturer/mentorship/students/$id/kpi-target/'
      path: '/'
      fullPath: '/mentorship/students/$id/kpi-target/'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsIdKpiTargetIndexRouteImport
      parentRoute: typeof AuthLecturerMentorshipStudentsIdKpiTargetRoute
    }
    '/_auth/_staff/staff/mentorships/students/$id/kpi-target': {
      id: '/_auth/_staff/staff/mentorships/students/$id/kpi-target'
      path: '/kpi-target'
      fullPath: '/staff/mentorships/students/$id/kpi-target'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsStudentsIdKpiTargetRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsStudentsIdRouteRoute
    }
    '/_auth/_staff/staff/mentorships/students/$id/kpi-records': {
      id: '/_auth/_staff/staff/mentorships/students/$id/kpi-records'
      path: '/kpi-records'
      fullPath: '/staff/mentorships/students/$id/kpi-records'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsStudentsIdKpiRecordsRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsStudentsIdRouteRoute
    }
    '/_auth/_staff/staff/mentorships/students/$id/challenges': {
      id: '/_auth/_staff/staff/mentorships/students/$id/challenges'
      path: '/challenges'
      fullPath: '/staff/mentorships/students/$id/challenges'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsStudentsIdChallengesRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsStudentsIdRouteRoute
    }
    '/_auth/_staff/staff/mentorships/students/$id/academics': {
      id: '/_auth/_staff/staff/mentorships/students/$id/academics'
      path: '/academics'
      fullPath: '/staff/mentorships/students/$id/academics'
      preLoaderRoute: typeof AuthStaffStaffMentorshipsStudentsIdAcademicsRouteImport
      parentRoute: typeof AuthStaffStaffMentorshipsStudentsIdRouteRoute
    }
    '/_auth/_lecturer/mentorship/students/$id/kpi-target/assign': {
      id: '/_auth/_lecturer/mentorship/students/$id/kpi-target/assign'
      path: '/assign'
      fullPath: '/mentorship/students/$id/kpi-target/assign'
      preLoaderRoute: typeof AuthLecturerMentorshipStudentsIdKpiTargetAssignRouteImport
      parentRoute: typeof AuthLecturerMentorshipStudentsIdKpiTargetRoute
    }
  }
}

interface AuthLecturerMentorshipStudentsIdKpiTargetRouteChildren {
  AuthLecturerMentorshipStudentsIdKpiTargetAssignRoute: typeof AuthLecturerMentorshipStudentsIdKpiTargetAssignRoute
  AuthLecturerMentorshipStudentsIdKpiTargetIndexRoute: typeof AuthLecturerMentorshipStudentsIdKpiTargetIndexRoute
}

const AuthLecturerMentorshipStudentsIdKpiTargetRouteChildren: AuthLecturerMentorshipStudentsIdKpiTargetRouteChildren =
  {
    AuthLecturerMentorshipStudentsIdKpiTargetAssignRoute:
      AuthLecturerMentorshipStudentsIdKpiTargetAssignRoute,
    AuthLecturerMentorshipStudentsIdKpiTargetIndexRoute:
      AuthLecturerMentorshipStudentsIdKpiTargetIndexRoute,
  }

const AuthLecturerMentorshipStudentsIdKpiTargetRouteWithChildren =
  AuthLecturerMentorshipStudentsIdKpiTargetRoute._addFileChildren(
    AuthLecturerMentorshipStudentsIdKpiTargetRouteChildren,
  )

interface AuthLecturerMentorshipStudentsIdRouteRouteChildren {
  AuthLecturerMentorshipStudentsIdAcademicsRoute: typeof AuthLecturerMentorshipStudentsIdAcademicsRoute
  AuthLecturerMentorshipStudentsIdChallengesRoute: typeof AuthLecturerMentorshipStudentsIdChallengesRoute
  AuthLecturerMentorshipStudentsIdKpiRecordsRoute: typeof AuthLecturerMentorshipStudentsIdKpiRecordsRoute
  AuthLecturerMentorshipStudentsIdKpiTargetRoute: typeof AuthLecturerMentorshipStudentsIdKpiTargetRouteWithChildren
  AuthLecturerMentorshipStudentsIdIndexRoute: typeof AuthLecturerMentorshipStudentsIdIndexRoute
}

const AuthLecturerMentorshipStudentsIdRouteRouteChildren: AuthLecturerMentorshipStudentsIdRouteRouteChildren =
  {
    AuthLecturerMentorshipStudentsIdAcademicsRoute:
      AuthLecturerMentorshipStudentsIdAcademicsRoute,
    AuthLecturerMentorshipStudentsIdChallengesRoute:
      AuthLecturerMentorshipStudentsIdChallengesRoute,
    AuthLecturerMentorshipStudentsIdKpiRecordsRoute:
      AuthLecturerMentorshipStudentsIdKpiRecordsRoute,
    AuthLecturerMentorshipStudentsIdKpiTargetRoute:
      AuthLecturerMentorshipStudentsIdKpiTargetRouteWithChildren,
    AuthLecturerMentorshipStudentsIdIndexRoute:
      AuthLecturerMentorshipStudentsIdIndexRoute,
  }

const AuthLecturerMentorshipStudentsIdRouteRouteWithChildren =
  AuthLecturerMentorshipStudentsIdRouteRoute._addFileChildren(
    AuthLecturerMentorshipStudentsIdRouteRouteChildren,
  )

interface AuthLecturerMentorshipStudentsRouteChildren {
  AuthLecturerMentorshipStudentsIdRouteRoute: typeof AuthLecturerMentorshipStudentsIdRouteRouteWithChildren
}

const AuthLecturerMentorshipStudentsRouteChildren: AuthLecturerMentorshipStudentsRouteChildren =
  {
    AuthLecturerMentorshipStudentsIdRouteRoute:
      AuthLecturerMentorshipStudentsIdRouteRouteWithChildren,
  }

const AuthLecturerMentorshipStudentsRouteWithChildren =
  AuthLecturerMentorshipStudentsRoute._addFileChildren(
    AuthLecturerMentorshipStudentsRouteChildren,
  )

interface AuthLecturerMentorshipRouteRouteChildren {
  AuthLecturerMentorshipMentorshipIdRoute: typeof AuthLecturerMentorshipMentorshipIdRoute
  AuthLecturerMentorshipAssignRoute: typeof AuthLecturerMentorshipAssignRoute
  AuthLecturerMentorshipStudentsRoute: typeof AuthLecturerMentorshipStudentsRouteWithChildren
  AuthLecturerMentorshipIndexRoute: typeof AuthLecturerMentorshipIndexRoute
}

const AuthLecturerMentorshipRouteRouteChildren: AuthLecturerMentorshipRouteRouteChildren =
  {
    AuthLecturerMentorshipMentorshipIdRoute:
      AuthLecturerMentorshipMentorshipIdRoute,
    AuthLecturerMentorshipAssignRoute: AuthLecturerMentorshipAssignRoute,
    AuthLecturerMentorshipStudentsRoute:
      AuthLecturerMentorshipStudentsRouteWithChildren,
    AuthLecturerMentorshipIndexRoute: AuthLecturerMentorshipIndexRoute,
  }

const AuthLecturerMentorshipRouteRouteWithChildren =
  AuthLecturerMentorshipRouteRoute._addFileChildren(
    AuthLecturerMentorshipRouteRouteChildren,
  )

interface AuthLecturerRouteRouteChildren {
  AuthLecturerMentorshipRouteRoute: typeof AuthLecturerMentorshipRouteRouteWithChildren
}

const AuthLecturerRouteRouteChildren: AuthLecturerRouteRouteChildren = {
  AuthLecturerMentorshipRouteRoute:
    AuthLecturerMentorshipRouteRouteWithChildren,
}

const AuthLecturerRouteRouteWithChildren =
  AuthLecturerRouteRoute._addFileChildren(AuthLecturerRouteRouteChildren)

interface AuthStaffStaffIntakeRouteRouteChildren {
  AuthStaffStaffIntakeAssignKpiRoute: typeof AuthStaffStaffIntakeAssignKpiRoute
  AuthStaffStaffIntakeIndexRoute: typeof AuthStaffStaffIntakeIndexRoute
}

const AuthStaffStaffIntakeRouteRouteChildren: AuthStaffStaffIntakeRouteRouteChildren =
  {
    AuthStaffStaffIntakeAssignKpiRoute: AuthStaffStaffIntakeAssignKpiRoute,
    AuthStaffStaffIntakeIndexRoute: AuthStaffStaffIntakeIndexRoute,
  }

const AuthStaffStaffIntakeRouteRouteWithChildren =
  AuthStaffStaffIntakeRouteRoute._addFileChildren(
    AuthStaffStaffIntakeRouteRouteChildren,
  )

interface AuthStaffStaffMentorshipsStudentsIdRouteRouteChildren {
  AuthStaffStaffMentorshipsStudentsIdAcademicsRoute: typeof AuthStaffStaffMentorshipsStudentsIdAcademicsRoute
  AuthStaffStaffMentorshipsStudentsIdChallengesRoute: typeof AuthStaffStaffMentorshipsStudentsIdChallengesRoute
  AuthStaffStaffMentorshipsStudentsIdKpiRecordsRoute: typeof AuthStaffStaffMentorshipsStudentsIdKpiRecordsRoute
  AuthStaffStaffMentorshipsStudentsIdKpiTargetRoute: typeof AuthStaffStaffMentorshipsStudentsIdKpiTargetRoute
  AuthStaffStaffMentorshipsStudentsIdIndexRoute: typeof AuthStaffStaffMentorshipsStudentsIdIndexRoute
}

const AuthStaffStaffMentorshipsStudentsIdRouteRouteChildren: AuthStaffStaffMentorshipsStudentsIdRouteRouteChildren =
  {
    AuthStaffStaffMentorshipsStudentsIdAcademicsRoute:
      AuthStaffStaffMentorshipsStudentsIdAcademicsRoute,
    AuthStaffStaffMentorshipsStudentsIdChallengesRoute:
      AuthStaffStaffMentorshipsStudentsIdChallengesRoute,
    AuthStaffStaffMentorshipsStudentsIdKpiRecordsRoute:
      AuthStaffStaffMentorshipsStudentsIdKpiRecordsRoute,
    AuthStaffStaffMentorshipsStudentsIdKpiTargetRoute:
      AuthStaffStaffMentorshipsStudentsIdKpiTargetRoute,
    AuthStaffStaffMentorshipsStudentsIdIndexRoute:
      AuthStaffStaffMentorshipsStudentsIdIndexRoute,
  }

const AuthStaffStaffMentorshipsStudentsIdRouteRouteWithChildren =
  AuthStaffStaffMentorshipsStudentsIdRouteRoute._addFileChildren(
    AuthStaffStaffMentorshipsStudentsIdRouteRouteChildren,
  )

interface AuthStaffStaffMentorshipsRouteRouteChildren {
  AuthStaffStaffMentorshipsMentorshipIdRoute: typeof AuthStaffStaffMentorshipsMentorshipIdRoute
  AuthStaffStaffMentorshipsAssignRoute: typeof AuthStaffStaffMentorshipsAssignRoute
  AuthStaffStaffMentorshipsIndexRoute: typeof AuthStaffStaffMentorshipsIndexRoute
  AuthStaffStaffMentorshipsStudentsIdRouteRoute: typeof AuthStaffStaffMentorshipsStudentsIdRouteRouteWithChildren
}

const AuthStaffStaffMentorshipsRouteRouteChildren: AuthStaffStaffMentorshipsRouteRouteChildren =
  {
    AuthStaffStaffMentorshipsMentorshipIdRoute:
      AuthStaffStaffMentorshipsMentorshipIdRoute,
    AuthStaffStaffMentorshipsAssignRoute: AuthStaffStaffMentorshipsAssignRoute,
    AuthStaffStaffMentorshipsIndexRoute: AuthStaffStaffMentorshipsIndexRoute,
    AuthStaffStaffMentorshipsStudentsIdRouteRoute:
      AuthStaffStaffMentorshipsStudentsIdRouteRouteWithChildren,
  }

const AuthStaffStaffMentorshipsRouteRouteWithChildren =
  AuthStaffStaffMentorshipsRouteRoute._addFileChildren(
    AuthStaffStaffMentorshipsRouteRouteChildren,
  )

interface AuthStaffStaffStudentsIdRouteRouteChildren {
  AuthStaffStaffStudentsIdAcademicsRoute: typeof AuthStaffStaffStudentsIdAcademicsRoute
  AuthStaffStaffStudentsIdChallengesRoute: typeof AuthStaffStaffStudentsIdChallengesRoute
  AuthStaffStaffStudentsIdKpiRecordsRoute: typeof AuthStaffStaffStudentsIdKpiRecordsRoute
  AuthStaffStaffStudentsIdKpiTargetRoute: typeof AuthStaffStaffStudentsIdKpiTargetRoute
  AuthStaffStaffStudentsIdIndexRoute: typeof AuthStaffStaffStudentsIdIndexRoute
}

const AuthStaffStaffStudentsIdRouteRouteChildren: AuthStaffStaffStudentsIdRouteRouteChildren =
  {
    AuthStaffStaffStudentsIdAcademicsRoute:
      AuthStaffStaffStudentsIdAcademicsRoute,
    AuthStaffStaffStudentsIdChallengesRoute:
      AuthStaffStaffStudentsIdChallengesRoute,
    AuthStaffStaffStudentsIdKpiRecordsRoute:
      AuthStaffStaffStudentsIdKpiRecordsRoute,
    AuthStaffStaffStudentsIdKpiTargetRoute:
      AuthStaffStaffStudentsIdKpiTargetRoute,
    AuthStaffStaffStudentsIdIndexRoute: AuthStaffStaffStudentsIdIndexRoute,
  }

const AuthStaffStaffStudentsIdRouteRouteWithChildren =
  AuthStaffStaffStudentsIdRouteRoute._addFileChildren(
    AuthStaffStaffStudentsIdRouteRouteChildren,
  )

interface AuthStaffStaffStudentsRouteRouteChildren {
  AuthStaffStaffStudentsIdRouteRoute: typeof AuthStaffStaffStudentsIdRouteRouteWithChildren
  AuthStaffStaffStudentsIndexRoute: typeof AuthStaffStaffStudentsIndexRoute
}

const AuthStaffStaffStudentsRouteRouteChildren: AuthStaffStaffStudentsRouteRouteChildren =
  {
    AuthStaffStaffStudentsIdRouteRoute:
      AuthStaffStaffStudentsIdRouteRouteWithChildren,
    AuthStaffStaffStudentsIndexRoute: AuthStaffStaffStudentsIndexRoute,
  }

const AuthStaffStaffStudentsRouteRouteWithChildren =
  AuthStaffStaffStudentsRouteRoute._addFileChildren(
    AuthStaffStaffStudentsRouteRouteChildren,
  )

interface AuthStaffRouteRouteChildren {
  AuthStaffStaffIntakeRouteRoute: typeof AuthStaffStaffIntakeRouteRouteWithChildren
  AuthStaffStaffMentorshipsRouteRoute: typeof AuthStaffStaffMentorshipsRouteRouteWithChildren
  AuthStaffStaffStudentsRouteRoute: typeof AuthStaffStaffStudentsRouteRouteWithChildren
  AuthStaffStaffManageLecturersRoute: typeof AuthStaffStaffManageLecturersRoute
}

const AuthStaffRouteRouteChildren: AuthStaffRouteRouteChildren = {
  AuthStaffStaffIntakeRouteRoute: AuthStaffStaffIntakeRouteRouteWithChildren,
  AuthStaffStaffMentorshipsRouteRoute:
    AuthStaffStaffMentorshipsRouteRouteWithChildren,
  AuthStaffStaffStudentsRouteRoute:
    AuthStaffStaffStudentsRouteRouteWithChildren,
  AuthStaffStaffManageLecturersRoute: AuthStaffStaffManageLecturersRoute,
}

const AuthStaffRouteRouteWithChildren = AuthStaffRouteRoute._addFileChildren(
  AuthStaffRouteRouteChildren,
)

interface AuthStudentKpiAcademicsRouteRouteChildren {
  AuthStudentKpiAcademicsAnalyticsRoute: typeof AuthStudentKpiAcademicsAnalyticsRoute
  AuthStudentKpiAcademicsIndexRoute: typeof AuthStudentKpiAcademicsIndexRoute
}

const AuthStudentKpiAcademicsRouteRouteChildren: AuthStudentKpiAcademicsRouteRouteChildren =
  {
    AuthStudentKpiAcademicsAnalyticsRoute:
      AuthStudentKpiAcademicsAnalyticsRoute,
    AuthStudentKpiAcademicsIndexRoute: AuthStudentKpiAcademicsIndexRoute,
  }

const AuthStudentKpiAcademicsRouteRouteWithChildren =
  AuthStudentKpiAcademicsRouteRoute._addFileChildren(
    AuthStudentKpiAcademicsRouteRouteChildren,
  )

interface AuthStudentKpiRecordsRouteRouteChildren {
  AuthStudentKpiRecordsAnalyticsRoute: typeof AuthStudentKpiRecordsAnalyticsRoute
  AuthStudentKpiRecordsIndexRoute: typeof AuthStudentKpiRecordsIndexRoute
}

const AuthStudentKpiRecordsRouteRouteChildren: AuthStudentKpiRecordsRouteRouteChildren =
  {
    AuthStudentKpiRecordsAnalyticsRoute: AuthStudentKpiRecordsAnalyticsRoute,
    AuthStudentKpiRecordsIndexRoute: AuthStudentKpiRecordsIndexRoute,
  }

const AuthStudentKpiRecordsRouteRouteWithChildren =
  AuthStudentKpiRecordsRouteRoute._addFileChildren(
    AuthStudentKpiRecordsRouteRouteChildren,
  )

interface AuthStudentKpiTargetRouteRouteChildren {
  AuthStudentKpiTargetEditRoute: typeof AuthStudentKpiTargetEditRoute
  AuthStudentKpiTargetIndexRoute: typeof AuthStudentKpiTargetIndexRoute
}

const AuthStudentKpiTargetRouteRouteChildren: AuthStudentKpiTargetRouteRouteChildren =
  {
    AuthStudentKpiTargetEditRoute: AuthStudentKpiTargetEditRoute,
    AuthStudentKpiTargetIndexRoute: AuthStudentKpiTargetIndexRoute,
  }

const AuthStudentKpiTargetRouteRouteWithChildren =
  AuthStudentKpiTargetRouteRoute._addFileChildren(
    AuthStudentKpiTargetRouteRouteChildren,
  )

interface AuthStudentRouteRouteChildren {
  AuthStudentKpiAcademicsRouteRoute: typeof AuthStudentKpiAcademicsRouteRouteWithChildren
  AuthStudentKpiRecordsRouteRoute: typeof AuthStudentKpiRecordsRouteRouteWithChildren
  AuthStudentKpiTargetRouteRoute: typeof AuthStudentKpiTargetRouteRouteWithChildren
  AuthStudentKpiChallengesRoute: typeof AuthStudentKpiChallengesRoute
  AuthStudentKpiOverviewRoute: typeof AuthStudentKpiOverviewRoute
}

const AuthStudentRouteRouteChildren: AuthStudentRouteRouteChildren = {
  AuthStudentKpiAcademicsRouteRoute:
    AuthStudentKpiAcademicsRouteRouteWithChildren,
  AuthStudentKpiRecordsRouteRoute: AuthStudentKpiRecordsRouteRouteWithChildren,
  AuthStudentKpiTargetRouteRoute: AuthStudentKpiTargetRouteRouteWithChildren,
  AuthStudentKpiChallengesRoute: AuthStudentKpiChallengesRoute,
  AuthStudentKpiOverviewRoute: AuthStudentKpiOverviewRoute,
}

const AuthStudentRouteRouteWithChildren =
  AuthStudentRouteRoute._addFileChildren(AuthStudentRouteRouteChildren)

interface AuthSettingsRouteRouteChildren {
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsUserSessionsRoute: typeof AuthSettingsUserSessionsRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsUserSessionsRoute: AuthSettingsUserSessionsRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthLecturerRouteRoute: typeof AuthLecturerRouteRouteWithChildren
  AuthStaffRouteRoute: typeof AuthStaffRouteRouteWithChildren
  AuthStudentRouteRoute: typeof AuthStudentRouteRouteWithChildren
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLecturerRouteRoute: AuthLecturerRouteRouteWithChildren,
  AuthStaffRouteRoute: AuthStaffRouteRouteWithChildren,
  AuthStudentRouteRoute: AuthStudentRouteRouteWithChildren,
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
